// Assembles the GitHub Wiki from both library surfaces and checks it.
//
// The wiki carries one reference per language, and each is generated by the toolchain that
// language documents itself with: TypeDoc writes the TypeScript pages into
// `typescript/docs/wiki` before this runs, and `dotnet-api.mjs` writes the .NET pages from
// the C# source. This script brings them together under `docs/wiki`, gives the wiki its
// shared landing page, builds the navigation and fails on a broken link.
//
// Run it from anywhere:
//
//     node scripts/wiki/build.mjs
//
// It needs TypeDoc's output to already exist, which is why `pnpm run docs` runs both.

import { execFileSync } from "node:child_process";
import {
  cp,
  mkdir,
  readFile,
  readdir,
  rename,
  rm,
  writeFile,
} from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { writeDotnetPages } from "./dotnet-api.mjs";
import { buildSidebars } from "./sidebar.mjs";
import { checkLinks } from "./check-links.mjs";

const repositoryRoot = fileURLToPath(new URL("../../", import.meta.url));
const wikiDir = join(repositoryRoot, "docs/wiki");
const typedocDir = join(repositoryRoot, "typescript/docs/wiki");

/** The page names the two surfaces present themselves under. */
const typescriptHome = "TypeScript";
const dotnetHome = "DotNet";
const sharedHome = "Home";

/** The revision the `Defined in:` links point at, so a line number matches the source. */
function currentCommit() {
  try {
    return execFileSync("git", ["rev-parse", "HEAD"], {
      cwd: repositoryRoot,
      encoding: "utf8",
    }).trim();
  } catch {
    return "main";
  }
}

/** The version the .NET project publishes, for the reference index's heading. */
async function dotnetVersion() {
  const project = await readFile(
    join(
      repositoryRoot,
      "dotnet/src/EliteDangerousAlmanac/EliteDangerousAlmanac.csproj",
    ),
    "utf8",
  );
  const version = /<Version>([^<]+)<\/Version>/.exec(project);
  if (!version)
    throw new Error("EliteDangerousAlmanac.csproj states no <Version>");
  return version[1];
}

async function main() {
  await rm(wikiDir, { recursive: true, force: true });
  await mkdir(wikiDir, { recursive: true });

  const generated = await readdir(typedocDir).catch(() => {
    throw new Error(
      `${typedocDir} does not exist — run TypeDoc first (\`pnpm run docs\` in typescript/)`,
    );
  });
  if (!generated.includes("Home.md")) {
    throw new Error(
      `${typedocDir} holds no Home.md — did TypeDoc write its readme page?`,
    );
  }
  for (const entry of generated) {
    if (!entry.endsWith(".md") || entry === "_Sidebar.md") continue;
    await cp(join(typedocDir, entry), join(wikiDir, entry));
  }
  // TypeDoc calls its readme page `Home`, which is the wiki's landing page rather than
  // the TypeScript surface's. The landing page is shared, so the surface takes its own
  // name and `Home` is written below.
  await rename(join(wikiDir, "Home.md"), join(wikiDir, `${typescriptHome}.md`));

  const dotnet = await writeDotnetPages({
    wikiDir,
    repositoryRoot,
    commit: currentCommit(),
    version: await dotnetVersion(),
  });

  await writeFile(
    join(wikiDir, `${sharedHome}.md`),
    await readFile(join(repositoryRoot, "docs/wiki-home.md"), "utf8"),
  );
  await writeFile(
    join(wikiDir, `${dotnetHome}.md`),
    await readFile(join(repositoryRoot, "dotnet/docs/wiki-home.md"), "utf8"),
  );

  await buildSidebars({
    wikiDir,
    home: sharedHome,
    surfaces: [
      {
        key: "typescript",
        title: "TypeScript",
        directory: "typescript",
        home: { target: typescriptHome, title: "Overview" },
        index: { target: "modules", title: "API reference" },
        guidesSection: "Documents",
        areasSection: "Modules",
        // The TypeScript reference publishes a handful of classes and a great many
        // free functions, so a class is worth expanding to its own members.
        expandMembers: true,
        // Its split catalogues sit on subpaths of the area that does not re-export
        // them, and belong under that area rather than beside it.
        subpaths: true,
      },
      {
        key: "dotnet",
        title: ".NET",
        directory: "dotnet",
        home: { target: dotnetHome, title: "Overview" },
        index: { target: dotnet.index, title: "API reference" },
        guidesSection: "Guides",
        areasSection: "Namespaces",
        // Nearly every .NET symbol is a type, so expanding each one's members in
        // place would make the tree longer than the reference it navigates.
        expandMembers: false,
        subpaths: false,
      },
    ],
  });

  await checkLinks(wikiDir);

  const pages = (await readdir(wikiDir, { recursive: true })).filter((entry) =>
    entry.endsWith(".md"),
  );
  process.stdout.write(`wiki assembled at docs/wiki (${pages.length} files)\n`);
}

await main();
