/**
 * Data-free shield collapse, regeneration and cell-bank aggregation calculations.
 *
 * Recovery timing is ported from EDCD/Coriolis at the revision recorded in
 * [`data/ships/SOURCES.md`](https://github.com/DarkSession/Elite-Dangerous-Almanac/blob/main/data/ships/SOURCES.md);
 * see [`ATTRIBUTIONS.md`](https://github.com/DarkSession/Elite-Dangerous-Almanac/blob/main/ATTRIBUTIONS.md).
 *
 * @packageDocumentation
 */

/** Everything {@link shieldRecovery} needs about a powered shield and SYS capacitor. */
export interface ShieldRecoveryInput {
    /** Total shield strength, including boosters and reinforcement, in megajoules. */
    readonly strength: number;
    /** Generator regeneration rate while the shield is raised, in MJ/s. */
    readonly regenRate: number;
    /** Generator regeneration rate while the shield is broken, in MJ/s. */
    readonly brokenRegenRate: number;
    /** SYS-capacitor energy spent per 1 MJ regenerated. */
    readonly distributorDraw: number;
    /** Fitted power distributor's SYS capacity. Zero when no distributor is fitted. */
    readonly systemsCapacity: number;
    /** Fitted power distributor's maximum SYS recharge rate, per second. */
    readonly systemsRecharge: number;
    /** Pips assigned to SYS, in `[0, 4]`. Defaults to `4`. */
    readonly systemsPips?: number;
}

/** Time and rates for a shield to return after collapsing. */
export interface ShieldRecovery {
    /** Megajoules per second regenerated while the shield is raised. */
    readonly regenRate: number;
    /** Megajoules per second regenerated while the shield is broken. */
    readonly brokenRegenRate: number;
    /** Seconds from collapse to the 50% threshold where the shield rises, including the 16 s delay. */
    readonly recoveryTime: number;
    /** Seconds from the 50% threshold to full strength. */
    readonly regenTime: number;
}

/** One fitted shield cell bank, reduced to the figures used by {@link cellBankSummary}. */
export interface CellBankInput {
    /** Slot key carrying the bank. */
    readonly slot: string;
    /** Module symbol. */
    readonly symbol: string;
    /** Shield reinforcement rate while one cell runs, in MJ/s. */
    readonly reinforcementRate: number;
    /** Cells carried when fully rearmed. */
    readonly cells: number;
    /** Delay before reinforcement starts, in seconds. */
    readonly spinUp: number;
    /** Reinforcement duration, in seconds. */
    readonly duration: number;
    /** Heat generated by one activation, in the game's thermal-load units. */
    readonly heat: number;
}

/** One fitted bank as exposed in a {@link CellBankSummary}. */
export interface CellBankMetrics {
    /** Slot key carrying the bank. */
    readonly slot: string;
    /** Module symbol. */
    readonly symbol: string;
    /** Megajoules restored by one complete cell activation. */
    readonly reinforcement: number;
    /** Cells carried when fully rearmed. */
    readonly cells: number;
    /** Delay before reinforcement starts, in seconds. */
    readonly spinUp: number;
    /** Reinforcement duration, in seconds. */
    readonly duration: number;
    /** Heat generated by one activation, in the game's thermal-load units. */
    readonly heat: number;
}

/** Every fitted shield cell bank and its combined pool. */
export interface CellBankSummary {
    /** Fitted banks in slot order. */
    readonly banks: readonly CellBankMetrics[];
    /** Megajoules restorable across every bank and cell. */
    readonly totalRestorable: number;
    /** Cells aboard across every fitted bank. */
    readonly totalCells: number;
}

const phaseTime = (
    megajoules: number,
    rate: number,
    draw: number,
    capacity: number,
    recharge: number,
): number => {
    if (megajoules <= 0) return 0;
    if (rate <= 0) return Infinity;
    if (draw <= 0) return megajoules / rate;
    const drain = rate * draw - recharge;
    if (drain <= 0) return megajoules / rate;
    const capacitorLifetime = capacity / drain;
    const beforeEmpty = capacitorLifetime * rate;
    if (megajoules <= beforeEmpty) return megajoules / rate;
    if (recharge <= 0) return Infinity;
    return capacitorLifetime + (megajoules - beforeEmpty) / (recharge / draw);
};

/**
 * Calculate shield recovery and regeneration times at one SYS-pip allocation.
 *
 * @param input - Shield strength, generator rates and power-distributor figures.
 * @returns Rates and seconds to 50%/100%. A phase that cannot finish returns `Infinity`.
 * @throws {RangeError} If `systemsPips` is outside `[0, 4]` or not finite.
 * @example
 * ```ts
 * import { shieldRecovery } from '@elite-dangerous-almanac/core/ships/shield-recovery';
 *
 * shieldRecovery({
 *   strength: 200, regenRate: 2, brokenRegenRate: 4,
 *   distributorDraw: 0.6, systemsCapacity: 20, systemsRecharge: 2,
 * }).recoveryTime; // -> 41
 * ```
 */
export function shieldRecovery(input: ShieldRecoveryInput): ShieldRecovery {
    const pips = input.systemsPips ?? 4;
    if (!Number.isFinite(pips) || pips < 0 || pips > 4) {
        throw new RangeError('shieldRecovery: systemsPips must be a finite number from 0 to 4');
    }
    const recharge = input.systemsRecharge * Math.pow(pips / 4, 1.1);
    const half = input.strength / 2;
    return {
        regenRate: input.regenRate,
        brokenRegenRate: input.brokenRegenRate,
        recoveryTime:
            16 +
            phaseTime(
                half,
                input.brokenRegenRate,
                input.distributorDraw,
                input.systemsCapacity,
                recharge,
            ),
        regenTime: phaseTime(
            half,
            input.regenRate,
            input.distributorDraw,
            input.systemsCapacity,
            recharge,
        ),
    };
}

/**
 * Aggregate fitted shield cell banks.
 *
 * @param banks - Banks in the order their slots should be reported.
 * @returns Frozen per-bank metrics and totals. An empty input returns an empty bank list and zero totals.
 * @example
 * ```ts
 * import { cellBankSummary } from '@elite-dangerous-almanac/core/ships/shield-recovery';
 *
 * cellBankSummary([{
 *   slot: 'Slot01_Size6', symbol: 'bank', reinforcementRate: 12,
 *   cells: 4, spinUp: 5, duration: 1, heat: 170,
 * }]).totalRestorable; // -> 48
 * ```
 */
export function cellBankSummary(banks: readonly CellBankInput[]): CellBankSummary {
    const metrics = banks.map((bank) =>
        Object.freeze({
            slot: bank.slot,
            symbol: bank.symbol,
            reinforcement: bank.reinforcementRate * bank.duration,
            cells: bank.cells,
            spinUp: bank.spinUp,
            duration: bank.duration,
            heat: bank.heat,
        }),
    );
    return Object.freeze({
        banks: Object.freeze(metrics),
        totalRestorable: metrics.reduce((sum, bank) => sum + bank.reinforcement * bank.cells, 0),
        totalCells: metrics.reduce((sum, bank) => sum + bank.cells, 0),
    });
}
