/**
 * Data-free shield collapse, regeneration and cell-bank aggregation calculations.
 *
 * Recovery timing is ported from EDCD/Coriolis at the revision recorded in
 * [`data/ships/SOURCES.md`](https://github.com/DarkSession/Elite-Dangerous-Almanac/blob/main/data/ships/SOURCES.md);
 * see [`ATTRIBUTIONS.md`](https://github.com/DarkSession/Elite-Dangerous-Almanac/blob/main/ATTRIBUTIONS.md).
 *
 * @packageDocumentation
 */

import { capacitorRechargeAtPips } from './internal/capacitor-recharge.js';

/** Everything {@link shieldRecovery} needs about a powered shield and SYS capacitor. */
export interface ShieldRecoveryInput {
    /** Finite non-negative total shield strength, including reinforcement, in megajoules. */
    readonly strength: number;
    /** Finite non-negative generator regeneration rate while the shield is raised, in MJ/s. */
    readonly regenRate: number;
    /** Finite non-negative generator regeneration rate while the shield is broken, in MJ/s. */
    readonly brokenRegenRate: number;
    /** Finite non-negative SYS-capacitor energy spent per 1 MJ regenerated. */
    readonly distributorDraw: number;
    /** Finite non-negative SYS capacity. Zero when no distributor is fitted. */
    readonly systemsCapacity: number;
    /** Finite non-negative maximum SYS recharge rate, per second. */
    readonly systemsRecharge: number;
    /** Finite pips assigned to SYS, in `[0, 4]`. Defaults to `4`. */
    readonly systemsPips?: number;
}

/**
 * Time and rates for a shield to return after collapsing.
 *
 * @remarks
 * Frozen — nested records and lists included — so a result can be held, cached and
 * shared without a defensive copy. Derive a changed figure with a spread rather than
 * by assigning into one.
 */
export interface ShieldRecovery {
    /** Megajoules per second regenerated while the shield is raised. */
    readonly regenRate: number;
    /** Megajoules per second regenerated while the shield is broken. */
    readonly brokenRegenRate: number;
    /** Seconds from collapse to the 50% threshold where the shield rises, including the 16 s delay. */
    readonly recoveryTime: number;
    /** Seconds from the 50% threshold to full strength. */
    readonly regenTime: number;
}

/** One fitted shield cell bank, reduced to the figures used by {@link cellBankSummary}. */
export interface CellBankInput {
    /** Slot key carrying the bank. */
    readonly slot: string;
    /** Module symbol. */
    readonly symbol: string;
    /** Shield reinforcement rate while one cell runs, in MJ/s. */
    readonly reinforcementRate: number;
    /** Cells carried when fully rearmed. */
    readonly cells: number;
    /** Delay before reinforcement starts, in seconds. */
    readonly spinUp: number;
    /** Reinforcement duration, in seconds. */
    readonly duration: number;
    /** Heat generated by one activation, in the game's thermal-load units. */
    readonly heat: number;
    /** Whether the fitted bank is switched on and receiving power. Must be a boolean. */
    readonly powered: boolean;
}

/** One fitted bank as exposed in a {@link CellBankSummary}. */
export interface CellBankMetrics {
    /** Slot key carrying the bank. */
    readonly slot: string;
    /** Module symbol. */
    readonly symbol: string;
    /** Megajoules restored by one complete cell activation. */
    readonly reinforcement: number;
    /** Cells carried when fully rearmed. */
    readonly cells: number;
    /** Delay before reinforcement starts, in seconds. */
    readonly spinUp: number;
    /** Reinforcement duration, in seconds. */
    readonly duration: number;
    /** Heat generated by one activation, in the game's thermal-load units. */
    readonly heat: number;
    /** Whether the fitted bank is switched on and receiving power. */
    readonly powered: boolean;
}

/**
 * Every fitted shield cell bank and the combined pool available from powered banks.
 *
 * @remarks
 * Frozen — nested records and lists included — so a result can be held, cached and
 * shared without a defensive copy. Derive a changed figure with a spread rather than
 * by assigning into one.
 */
export interface CellBankSummary {
    /** Fitted banks in slot order. */
    readonly banks: readonly CellBankMetrics[];
    /** Megajoules restorable across every powered bank and cell. */
    readonly totalRestorable: number;
    /** Cells aboard across every powered bank. */
    readonly totalCells: number;
}

const phaseTime = (
    megajoules: number,
    rate: number,
    draw: number,
    capacity: number,
    recharge: number,
): number => {
    if (megajoules <= 0) return 0;
    if (rate <= 0) return Infinity;
    if (draw <= 0) return megajoules / rate;
    const drain = rate * draw - recharge;
    if (drain <= 0) return megajoules / rate;
    const capacitorLifetime = capacity / drain;
    const beforeEmpty = capacitorLifetime * rate;
    if (megajoules <= beforeEmpty) return megajoules / rate;
    if (recharge <= 0) return Infinity;
    return capacitorLifetime + (megajoules - beforeEmpty) / (recharge / draw);
};

const requireFiniteNonNegative = (name: string, value: number): void => {
    if (!Number.isFinite(value) || value < 0) {
        throw new RangeError(`shieldRecovery: ${name} must be a finite non-negative number`);
    }
};

/**
 * Calculate shield recovery and regeneration times at one SYS-pip allocation.
 *
 * @param input - Shield strength, generator rates and power-distributor figures.
 * @returns Rates and seconds to 50%/100%. A phase that cannot finish returns `Infinity`.
 * @throws {RangeError} If `systemsPips` is outside `[0, 4]`, or any numeric input is
 * negative or not finite.
 * @example
 * ```ts
 * import { shieldRecovery } from '@elite-dangerous-almanac/core/ships/shield-recovery';
 *
 * shieldRecovery({
 *   strength: 200, regenRate: 2, brokenRegenRate: 4,
 *   distributorDraw: 0.6, systemsCapacity: 20, systemsRecharge: 2,
 * }).recoveryTime; // -> 41
 * ```
 */
export function shieldRecovery(input: ShieldRecoveryInput): ShieldRecovery {
    const pips = input.systemsPips ?? 4;
    if (!Number.isFinite(pips) || pips < 0 || pips > 4) {
        throw new RangeError('shieldRecovery: systemsPips must be a finite number from 0 to 4');
    }
    for (const field of [
        'strength',
        'regenRate',
        'brokenRegenRate',
        'distributorDraw',
        'systemsCapacity',
        'systemsRecharge',
    ] as const) {
        requireFiniteNonNegative(field, input[field]);
    }
    const recharge = capacitorRechargeAtPips(input.systemsRecharge, pips);
    const half = input.strength / 2;
    return Object.freeze({
        regenRate: input.regenRate,
        brokenRegenRate: input.brokenRegenRate,
        recoveryTime:
            16 +
            phaseTime(
                half,
                input.brokenRegenRate,
                input.distributorDraw,
                input.systemsCapacity,
                recharge,
            ),
        regenTime: phaseTime(
            half,
            input.regenRate,
            input.distributorDraw,
            input.systemsCapacity,
            recharge,
        ),
    });
}

/**
 * Aggregate fitted shield cell banks while retaining their individual power state.
 *
 * @param banks - Banks in the order their slots should be reported.
 * @returns Frozen per-bank metrics and totals over powered banks. An empty input returns
 * an empty bank list and zero totals.
 * @throws {TypeError} If any bank's `powered` value is not a boolean.
 * @example
 * ```ts
 * import { cellBankSummary } from '@elite-dangerous-almanac/core/ships/shield-recovery';
 *
 * cellBankSummary([{
 *   slot: 'Slot01_Size6', symbol: 'bank', reinforcementRate: 12,
 *   cells: 4, spinUp: 5, duration: 1, heat: 170, powered: true,
 * }]).totalRestorable; // -> 48
 * ```
 */
export function cellBankSummary(banks: readonly CellBankInput[]): CellBankSummary {
    for (const [index, bank] of banks.entries()) {
        if (typeof bank.powered !== 'boolean') {
            throw new TypeError(`cellBankSummary: banks[${index}].powered must be a boolean`);
        }
    }
    const metrics = banks.map((bank) =>
        Object.freeze({
            slot: bank.slot,
            symbol: bank.symbol,
            reinforcement: bank.reinforcementRate * bank.duration,
            cells: bank.cells,
            spinUp: bank.spinUp,
            duration: bank.duration,
            heat: bank.heat,
            powered: bank.powered,
        }),
    );
    return Object.freeze({
        banks: Object.freeze(metrics),
        totalRestorable: metrics.reduce(
            (sum, bank) => sum + (bank.powered ? bank.reinforcement * bank.cells : 0),
            0,
        ),
        totalCells: metrics.reduce((sum, bank) => sum + (bank.powered ? bank.cells : 0), 0),
    });
}
