/**
 * Sparse, source-backed localized display names for Elite Dangerous outfitting and
 * engineering catalogues.
 *
 * Each lookup takes the same Frontier symbol as its owning catalogue and a BCP 47
 * locale. English is complete and exactly matches the owning record's `name`.
 * Other locales are intentionally sparse: the function returns `null` when its pinned
 * sources carry no translation, leaving the application in control of fallback policy.
 * A source-backed localized spelling can be identical to English; the lookup returns
 * explicit source values verbatim but never manufactures an English fallback.
 * The catalogues carry English, French, German, Portuguese, Russian and Spanish only,
 * each stored under a bare language tag: a regional or script subtag is dropped
 * (`de-DE` → `de`), and any other language is an unsupported locale.
 *
 * **How sparse, dataset by dataset.** Each column below is the percentage of that
 * lookup's keys carrying a stored value for the locale, so a `0` would mean the dataset
 * holds nothing in that language at all and the lookup returns `null` for every key:
 * German module names are near-complete, while a quarter of the outfitting families —
 * the ones the game does not name separately — have no locale at all. Plan fallback per
 * lookup rather than per application. The table is generated from `data/i18n/`, so it
 * moves when the data does.
 *
 * <!-- generated by scripts/i18n-coverage.mjs -->
 * | Lookup | Keys | en | de | es | fr | pt | ru |
 * | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
 * | `getBlueprintName` | 107 | 100 | 100 | 100 | 100 | 100 | 100 |
 * | `getExperimentalEffectDescription` | 86 | 100 | 100 | 100 | 100 | 100 | 100 |
 * | `getExperimentalEffectName` | 86 | 100 | 100 | 100 | 100 | 100 | 100 |
 * | `getMaterialName` | 146 | 100 | 100 | 100 | 100 | 100 | 100 |
 * | `getMicroResourceName` | 226 | 100 | 100 | 100 | 100 | 100 | 100 |
 * | `getModuleName` | 1199 | 100 | 100 | 100 | 100 | 100 | 100 |
 * | `getPreEngineeredVariantName` | 76 | 100 | 92 | 89 | 89 | 100 | 100 |
 * | `getOutfittingFamilyName` | 77 | 100 | 75 | 75 | 75 | 75 | 75 |
 * <!-- end generated -->
 *
 * Each dataset lives in a separate runtime module. Import from this barrel for
 * convenience or from the corresponding `i18n/*` subpath for an explicit bundle
 * boundary.
 *
 * Structured diagnostic helpers expose their current English fallback only for English
 * locales and return `null` otherwise, so a UI never mistakes English prose for a
 * requested translation. Stable codes and `params` remain available for applications
 * that supply their own message catalogues.
 *
 * @example
 * ```ts
 * import {
 *   getBlueprintName,
 *   getMaterialName,
 *   getModuleName,
 *   getOutfittingFamilyName,
 * } from '@elite-dangerous-almanac/core/i18n';
 *
 * getModuleName('Int_Hyperdrive_Size6_Class5', 'de'); // -> 'Frameshiftantrieb'
 * getBlueprintName('FSD_LongRange', 'de-DE'); // -> 'Erhöhte FSA-Reichweite'
 * getMaterialName('GridResistors', 'de'); // -> 'Gitterwiderstände'
 *
 * // Sparseness is per dataset, not per locale: German module names are near-complete,
 * // while no outfitting family the game does not name separately has any.
 * getOutfittingFamilyName('shieldGenerators', 'de'); // -> 'Schildgeneratoren'
 * getOutfittingFamilyName('xenoScanners', 'de'); // -> null
 * ```
 *
 * @packageDocumentation
 */

export { getModuleName } from './modules.js';
export { getOutfittingFamilyName } from './module-families.js';
export { getBlueprintName } from './blueprints.js';
export { getExperimentalEffectName } from './experimental-effects.js';
export { getExperimentalEffectDescription } from './experimental-effect-descriptions.js';
export { getMaterialName } from './materials.js';
export { getMicroResourceName } from './micro-resources.js';
export { getLoadoutSlotName, getSlotRestrictionLabel } from './slots.js';
export {
    getCalculationIssueMessage,
    getLoadoutEditErrorMessage,
    getLoadoutIssueMessage,
    getSlefDiagnosticMessage,
} from './diagnostics.js';
export {
    getPreEngineeredVariantName,
    type PreEngineeredVariantIdentity,
} from './pre-engineered.js';
export type { GameLocale } from './locale.js';
